# Generated by Django 2.0.7 on 2018-07-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='created_on',
            new_name='created',
        ),
    ]
