# Generated by Django 2.0.7 on 2018-07-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0002_auto_20180713_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('billing_address', models.TextField()),
                ('gt_vendor_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('unapproved', 'Unapproved'), ('approved', 'Approved'), ('preferred', 'Preferred'), ('unavailable', 'Unavailable')], max_length=24)),
                ('sales_contact', models.TextField(null=True)),
                ('customer_id', models.CharField(max_length=128, null=True)),
                ('web_account', models.BooleanField(default=False)),
                ('website', models.CharField(max_length=128, null=True)),
                ('part_url_schema', models.CharField(max_length=128, null=True)),
                ('shipping_quote_required', models.BooleanField(default=False)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('requisition_guidance', models.TextField(null=True)),
            ],
        ),
    ]
